Algoritmo "trocar valores"
// Disciplina   : [Programação e algoritimos]
// Autor(a)    : Gabryel henrique
// Data atual  : 19/03/2021
Var
// Seção de Declarações das variáveis
 a,b,c: inteiro
 
  inicio
  // Seção de Comandos, procedimento, funções, operadores, etc...
  a <- 15
  b <- 30

 escreval("o valor de A é: ",a)
 escreval("o valor de B é: ",b)

 c <- a
 a <- b
 b <- c
 
 escreval("o valor de A é: ",a)
 escreval("o valor de B é: ",b)

Fimalgoritmo